services:
  php:
    environment:
      - PHP_IDE_CONFIG=serverName=chequear-server
    container_name: php-server
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    volumes:
      - ./backend:/var/www/html
      - ./backend/docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./backend/docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    ports:
      - 8000:80
    depends_on:
      - mysql-db

  mysql-db:
    container_name: mysql-db
    image: mysql:9.0
    environment:
      MYSQL_ROOT_PASSWORD: globo
      MYSQL_DATABASE: futbollibre
      MYSQL_USER: axelcarlos
      MYSQL_PASSWORD: globito
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:3000"
    depends_on:
      - php

volumes:
  mysql_data: